name: GitHub container registry build and push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      -
        name: Confirm tag name
        run: echo "Tag name ${{ github.ref_name }}"
      -  
        name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}, ghcr.io/${{ env.REPO }}:${{ github.ref_name }}, ghcr.io/${{ env.REPO }}:latest
          push: True
